
services:
  - name: mysite
    type: web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portafolio.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
static_dirs:
  - static
        